// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZPdyh4xJ9KHjgKLELBloDwvihkON8lRc',
    appId: '1:432398520244:web:0ea73b4211e881e83eace1',
    messagingSenderId: '432398520244',
    projectId: 'farm24dec-mork',
    authDomain: 'farm24dec-mork.firebaseapp.com',
    storageBucket: 'farm24dec-mork.appspot.com',
    measurementId: 'G-8TLVJNVMD5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAARjzPQcG7IfBk3oZu0h_f0rY8HCabJ8o',
    appId: '1:432398520244:android:a42b89c0f92e01a43eace1',
    messagingSenderId: '432398520244',
    projectId: 'farm24dec-mork',
    storageBucket: 'farm24dec-mork.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCySX-DCbt30slPddJWJ19AaQtcjiGztKQ',
    appId: '1:432398520244:ios:18cbfba4be38c2a63eace1',
    messagingSenderId: '432398520244',
    projectId: 'farm24dec-mork',
    storageBucket: 'farm24dec-mork.appspot.com',
    iosBundleId: 'com.example.flutterCubitLoadmore',
  );
}
