// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions web = FirebaseOptions(
    apiKey: dotenv.get('FIREBASE_WEB_APIKEY'),
    appId: dotenv.get('FIREBASE_WEB_APPID'),
    messagingSenderId: dotenv.get('FIREBASE_WEB_MESSAGINGSENDERID'),
    projectId: dotenv.get('FIREBASE_WEB_PROJECTID'),
    authDomain: dotenv.get('FIREBASE_WEB_AUTHDOMAIN'),
    storageBucket: dotenv.get('FIREBASE_WEB_STORAGEBUCKET'),
    measurementId: dotenv.get('FIREBASE_WEB_MEASUREMENTID'),
  );

  static FirebaseOptions android = FirebaseOptions(
    apiKey: dotenv.get('FIREBASE_ANDROID_APIKEY'),
    appId: dotenv.get('FIREBASE_ANDROID_APPID'),
    messagingSenderId: dotenv.get('FIREBASE_ANDROID_MESSAGINGSENDERID'),
    projectId: dotenv.get('FIREBASE_ANDROID_PROJECTID'),
    storageBucket: dotenv.get('FIREBASE_ANDROID_STORAGEBUCKET'),
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: dotenv.get('FIREBASE_IOS_APIKEY'),
    appId: dotenv.get('FIREBASE_IOS_APPID'),
    messagingSenderId: dotenv.get('FIREBASE_IOS_MESSAGINGSENDERID'),
    projectId: dotenv.get('FIREBASE_IOS_PROJECTID'),
    storageBucket: dotenv.get('FIREBASE_IOS_STORAGEBUCKET'),
    iosBundleId: dotenv.get('FIREBASE_IOS_IOSBUNDLEID'),
  );
}
